server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stend_resources?useSSL=false&serverTimezone=Europe/Moscow
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
